# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: diane.af
email: diane@dianelooney.com
description: Be gay, do crime.
baseurl: ""
url: "https://diane.af"
github_username: dianelooney
paginate: 5
theme-dark: true #Set to true to change to dark website theme
collections:
  dailies:
    output: true

plugins: [jekyll-paginate, kramdown]
# Build settings
markdown: kramdown
